services:
  twingate_connector:  # Define a service named "twingate_connector"
    image: ${TG_IMAGE_NAME}  # Use the "twingate/connector" Docker image with the "latest" tag
    container_name: ${TG_LABEL_HOSTNAME}
    hostname: ${TG_LABEL_HOSTNAME}
    network_mode: host
    restart: always  # Ensure the container restarts automatically if it exits (e.g., after a crash or system reboot)
    environment:
#      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
#      - TWINGATE_API_ENDPOINT=/connector.stock
      - TWINGATE_NETWORK=${TG_NETWORK}
      - TWINGATE_ACCESS_TOKEN=${TG_ACCESS_TOKEN}
      - TWINGATE_REFRESH_TOKEN=${TG_REFRESH_TOKEN}
      - TWINGATE_LABEL_HOSTNAME=${TG_LABEL_HOSTNAME}
      - TWINGATE_LOG_ANALYTICS=v2
      - TWINGATE_LOG_LEVEL=4

#    sysctls:
#      - "net.ipv4.ping_group_range=0 65535"  # Set the sysctl parameter "net.ipv4.ping_group_range" to allow user IDs in the range 0 to 65535 to create ICMP echo request (ping) sockets
